// priority: 100
onEvent("recipes", (event) => {
  event.remove({output: 'mysticalagriculture:brass_essence'})
  event.remove({output: 'mysticalagriculture:brass_seeds'})
  event.remove({output: 'mysticalagriculture:iridium_seeds'})
  event.remove({output: 'mysticalagriculture:iridium_essence'})
  event.remove({output: 'mysticalagriculture:chrome_seeds'})
  event.remove({output: 'mysticalagriculture:platinum_seeds'})
  event.remove({output: 'mysticalagriculture:graphite_seeds'})
  event.remove({output: 'mysticalagriculture:tungsten_seeds'})
  event.remove({output: 'mysticalagriculture:mithril_seeds'})
  event.remove({output: 'mysticalagriculture:titanium_seeds'})
  event.remove({output: 'mysticalagriculture:platinum_essence'})
  event.remove({output: 'mysticalagriculture:graphite_essence'})
  event.remove({output: 'mysticalagriculture:tungsten_essence'})
  event.remove({output: 'mysticalagriculture:mithril_essence'})
  event.remove({output: 'mysticalagriculture:titanium_essence'})
  event.remove({output: 'mysticalagriculture:chrome_essence'})
  event.remove({output: 'extendedcrafting:handheld_table'})
  event.remove({output: 'mob_grinding_utils:nutritious_chicken_feed'})
  event.remove({output: 'mob_grinding_utils:gm_chicken_feed_cursed'})
  event.remove({output: 'mob_grinding_utils:entity_spawner'})
  event.remove({output: 'tombstone:book_of_recycling'})
  event.remove({output: 'pedestals:coin/rfmobgen'})
  event.remove({output: 'mob_grinding_utils:spikes'})
});
