events.listen('recipes', function (e) {
e.custom({
  "type": "masterfulmachinery:machine_structure",
  "id": "autoblood_machine",
  "controllerId": "autoblood",
  "name": "BloodAltar Machine",
  "layout": [
    [
      "              )))))           ",
      "              )))))           ",
      "              )))))           ",
      "              )))))           ",
      "    ))))))))))))))))))))))))) ",
      "    ))))))))))))))))))))))))) ",
      "    ))     )))))))))))     )) ",
      "    ))                     )) ",
      "    ))                     )) ",
      "    ))                     )) ",
      "    ))                     )) ",
      "    )))                   ))) ",
      "    )))                   ))) ",
      "    )))                   ))))",
      ")))))))                   )))*",
      ")))))))                   )))*",
      ")))))))                   )))*",
      ")))))))                   )))*",
      ")))))))                   )))*",
      "    )))                   ))))",
      "    )))                   ))) ",
      "    )))                   ))) ",
      "    ))                     )) ",
      "    ))                     )) ",
      "    ))                     )) ",
      "    ))                     )) ",
      "    ))     )))))))))))     )) ",
      "    ))))))))))))))))))))))))) ",
      "    ))))))))))))))))))))))))) ",
      "              )))))           ",
      "              )))))           ",
      "              )))))           ",
      "              )))))           "
    ],
    [
      "              )+++)           ",
      "              +   +           ",
      "              + + +           ",
      "              +   +           ",
      "    )+++++++++)   )+++++++++) ",
      "    +                       + ",
      "    + *****           ***** + ",
      "    + *,,,*************,,,* + ",
      "    + *,,,-.-.-.-.-.-.-,,,* + ",
      "    + *,,,))))))))))))),,,* + ",
      "    + **-)))))))))))))))-** + ",
      "    +  *.))           )).*  + ",
      "    +  *-))           ))-*  + ",
      "    +  *.))           )).*  )+",
      ")+++)  *-))           ))-*    ",
      "+      *.))           )).*    ",
      "+ +    *-))           ))-*    ",
      "+      *.))           )).*    ",
      ")+++)  *-))           ))-*    ",
      "    +  *.))           )).*  )+",
      "    +  *-))           ))-*  + ",
      "    +  *.))           )).*  + ",
      "    + **-)))))))))))))))-** + ",
      "    + *,,,))))))))))))),,,* + ",
      "    + *,,,-.-.-.-.-.-.-,,,* + ",
      "    + *,,,*************,,,* + ",
      "    + *****           ***** + ",
      "    +                       + ",
      "    )+++++++++)   )+++++++++) ",
      "              +   +           ",
      "              + + +           ",
      "              +   +           ",
      "              )+++)           "
    ],
    [
      "              )   )           ",
      "                              ",
      "                /             ",
      "                              ",
      "    0         )   )         0 ",
      "                              ",
      "                              ",
      "       1*1             1*1    ",
      "       *2*             *2*    ",
      "       1*1             1*1    ",
      "          *************       ",
      "          *))3434343))*       ",
      "          *)         )*       ",
      "          *3         3*     )5",
      ")   )     *4         4*       ",
      "          *3         3*       ",
      "  6       *4         4*       ",
      "          *3         3*       ",
      ")   )     *4         4*       ",
      "          *3         3*     )5",
      "          *)         )*       ",
      "          *))3434343))*       ",
      "          *************       ",
      "       1*1             1*1    ",
      "       *2*             *2*    ",
      "       1*1             1*1    ",
      "                              ",
      "                              ",
      "    0         )   )         0 ",
      "                              ",
      "                7             ",
      "                              ",
      "              )   )           "
    ],
    [
      "              0   0           ",
      "                              ",
      "                              ",
      "                              ",
      "    )         0   0         ) ",
      "                              ",
      "                              ",
      "                              ",
      "        8               8     ",
      "                              ",
      "                              ",
      "           )         )        ",
      "            *********         ",
      "            *)99499)*       0 ",
      "0   0       *9     9*         ",
      "            *9     9*         ",
      "            *4     4*         ",
      "            *9     9*         ",
      "0   0       *9     9*         ",
      "            *)99499)*       0 ",
      "            *********         ",
      "           )         )        ",
      "                              ",
      "                              ",
      "        8               8     ",
      "                              ",
      "                              ",
      "                              ",
      "    )         0   0         ) ",
      "                              ",
      "                              ",
      "                              ",
      "              0   0           "
    ],
    [
      "              )* *)           ",
      "              *   *           ",
      "                              ",
      "              *   *           ",
      "    +         )   )         + ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "           )         )        ",
      "                              ",
      "             )     )        ) ",
      ")* *)         *****           ",
      "*             *:::*           ",
      "              *: :*           ",
      "*             *:::*           ",
      ")* *)         *****           ",
      "             )     )        ) ",
      "                              ",
      "           )         )        ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "    +         )   )         + ",
      "              *   *           ",
      "                              ",
      "              *   *           ",
      "              )* *)           "
    ],
    [
      "               *)*            ",
      "              *1 1*           ",
      "              ) 5 )           ",
      "              *1 1*           ",
      "    5          *)*          5 ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "           0         )        ",
      "                              ",
      "             0     0        * ",
      " *)*                        * ",
      "*1 1*                         ",
      ") 5 )           ;             ",
      "*1 1*                         ",
      " *)*                        * ",
      "             0     0        * ",
      "                              ",
      "           0         0        ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "    5          *)*          5 ",
      "              *1 1*           ",
      "              ) 5 )           ",
      "              *1 1*           ",
      "               *)*            "
    ],
    [
      "                              ",
      "                1             ",
      "               1)1            ",
      "                1             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "           )         )        ",
      "                              ",
      "             <     <          ",
      "                            * ",
      "  1                         * ",
      " 1)1                          ",
      "  1                         * ",
      "                            * ",
      "             <     <          ",
      "                              ",
      "           )         )        ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                1             ",
      "               1)1            ",
      "                1             ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                )             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "           =         =        ",
      "                              ",
      "                              ",
      "                              ",
      "                            1 ",
      "  )             >           ) ",
      "                            1 ",
      "                              ",
      "                              ",
      "                              ",
      "           =         =        ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                )             ",
      "                              ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                )             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "  )             C          ** ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                )             ",
      "                              ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                *             ",
      "                *             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "               ***            ",
      "  **           *)*        **  ",
      "               ***            ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                *             ",
      "                *             ",
      "                              ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                              ",
      "                *             ",
      "                *             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "              *****           ",
      "              *)))*           ",
      "   **         *)))*      **   ",
      "              *)))*           ",
      "              *****           ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                *             ",
      "                *             ",
      "                              ",
      "                              ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                *             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "              **)**           ",
      "              *===*           ",
      "    *))))))))))===)))))))*    ",
      "              *===*           ",
      "              **)**           ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                )             ",
      "                *             ",
      "                              ",
      "                              ",
      "                              ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                +             ",
      "                              ",
      "              +   +           ",
      "                              ",
      "                +             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              "
    ],
    [
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                5             ",
      "                              ",
      "              5   5           ",
      "                              ",
      "                5             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              "
    ]
  ],
  "legend": {
    ")": {
      "block": "minecraft:polished_blackstone"
    },
    "*": {
      "block": "minecraft:polished_blackstone_stairs"
    },
    "+": {
      "block": "minecraft:polished_blackstone_wall"
    },
    ",": {
      "block": "minecraft:netherite_block"
    },
    "-": {
      "block": "bloodmagic:accelerationrune"
    },
    ".": {
      "block": "bloodmagic:blankrune"
    },
    "/": {
      "block": "masterfulmachinery:autoblood_blood_fluid_port_fluids_input"
    },
    "0": {
      "block": "minecraft:chiseled_polished_blackstone"
    },
    "1": {
      "block": "minecraft:polished_blackstone_slab"
    },
    "2": {
      "block": "minecraft:beacon"
    },
    "3": {
      "block": "bloodmagic:bettercapacityrune"
    },
    "4": {
      "block": "bloodmagic:altarcapacityrune"
    },
    "5": {
      "block": "minecraft:soul_lantern"
    },
    "6": {
      "block": "masterfulmachinery:autoblood_blood_item_port_items_output"
    },
    "7": {
      "block": "masterfulmachinery:autoblood_blood_item_port_items_input"
    },
    "8": {
      "block": "minecraft:red_stained_glass_pane"
    },
    "9": {
      "block": "bloodmagic:speedrune"
    },
    ":": {
      "block": "bloodmagic:sacrificerune"
    },
    ";": {
      "block": "bloodmagic:altar"
    },
    "<": {
      "block": "minecraft:glowstone"
    },
    "=": {
      "block": "bloodmagic:largebloodstonebrick"
    },
    ">": {
      "block": "minecraft:hopper"
    }
  }
})

  function bloodcraft(ticks, input, mb, output) {
    e.custom({
      "type": "masterfulmachinery:machine_process",
      "structureId": "autoblood_machine",
      "controllerId": "autoblood",
      "ticks": ticks,
      "inputs": [
          {"type": "masterfulmachinery:items","data": {"item": input,"count": 1}},
          {"type": "masterfulmachinery:fluids","data": {"fluid": "bloodmagic:life_essence_fluid","amount": mb}}
      ],
      "outputs": [{"type": "masterfulmachinery:items","data": {"item": output,"count": 1}}]
    })
  }

  bloodcraft(50 ,'minecraft:stone', 1000, 'bloodmagic:blankslate')
  bloodcraft(100 ,'bloodmagic:blankslate', 2000, 'bloodmagic:reinforcedslate')
  bloodcraft(100 ,'bloodmagic:reinforcedslate', 5000, 'bloodmagic:infusedslate')
  bloodcraft(180 ,'bloodmagic:infusedslate', 15000, 'bloodmagic:demonslate')
  bloodcraft(230 ,'bloodmagic:demonslate', 30000, 'bloodmagic:etherealslate')
})
