
[crop]
	#Determines if bonemeal can be applied to the animal crops, anemonemals, animal shrooms, and magnemones
	bonemeal = true
	#List of animals to add as animal seeds. Must extend MobEntity and have a spawn egg.
	animalCrops = ["minecraft:bee", "minecraft:cat", "minecraft:chicken", "minecraft:cow", "minecraft:donkey", "minecraft:fox", "minecraft:horse", "minecraft:llama", "minecraft:mooshroom", "minecraft:ocelot", "minecraft:panda", "minecraft:parrot", "minecraft:pig", "minecraft:polar_bear", "minecraft:rabbit", "minecraft:sheep", "minecraft:villager", "minecraft:wolf"]
	#List of water animals to add as water animal crops: anemonemals. Must extend MobEntity and have a spawn egg.
	anemonemals = ["minecraft:cod", "minecraft:dolphin", "minecraft:pufferfish", "minecraft:salmon", "minecraft:squid", "minecraft:tropical_fish", "minecraft:turtle"]
	#List of nether animals to add as nether animal shrooms. Must extend MobEntity and have a spawn egg.
	shrooms = ["minecraft:hoglin", "minecraft:piglin"]
	#List of lava animals to add as lava animal crops: magnemones. Must extend MobEntity and have a spawn egg.
	magnemones = ["minecraft:strider"]

[pollen]
	#If CONSUME, the entity is killed when pollen are used, though no items are dropped
	#If DAMAGE, the entity will take 2 hearts of damage when pollen are used
	#Allowed Values: CONSUME, DAMAGE, NONE
	action = "DAMAGE"
	#Animals that pollen cannot be used on, from either animal crops or anemonemals
	blacklist = []

[grassDrops]
	#If true, grass will rarely drop animal pollen
	animal_pollen = true
	#Animals that will not drop from grass or sea grass, based on the other two lists
	blacklist = []
	#If true, grass will rarely drop a random animal seed
	animal_seeds = false
	#If true, sea grass will rarely drop a random anemonemal
	anemonemal = false
	#If true, nether sprouts will rarely drop a random animal shroom
	animal_shrooms = false
	#If true, nether sprouts will rarely drop a random magnemones
	magnemones = false

